# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'iOS Project Structure' do
    pod "LoremIpsum", "~> 1.0.0"
    pod "Google/Analytics"
    pod "Fabric"
    pod "Crashlytics"
    pod "AFNetworking"
    pod "JSONModel"
    pod "Realm"
    pod "SDWebImage"
    pod "SVProgressHUD"
end
